services:
  backend:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/home/server/
      - modules:/home/server/node_modules
    env_file:
      - .env

    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    env_file:
      - .env

volumes:
  modules:

  
